name: ItemLoreRate
version: 1.0
main: me.blowyrioeyu.itemlorerate.itemlorerate
author: blowyrioeyu
commands:
  addlore:
    description: Thêm lore vào item đang cầm
    usage: /addlore <COMMON|UNCOMMON|RARE|EPIC|LEGENDARY>
